"use client";

import { useState, type ReactNode } from "react";

const FAQS: { q: string; a: ReactNode }[] = [
  {
    q: "How does TruKode work?",
    a: "Choose a Read, share your details through a calm guided experience, and we decode a personal report from your own data — bringing every dimension of who you are into one cohesive picture.",
  },
  {
    q: "What information do you need from me?",
    a: "Your name, date of birth, place of birth, and time of birth. For the Compatibility Read™, we'll also ask for a few details about your partner.",
  },
  {
    q: "How is my Read created?",
    a: "Each Read is generated by an advanced intelligence we've carefully trained on the most trusted, time-honored methods — numerology, psychology, archetypes, life-cycle phase, and spiritual insight — combined with precise calculations on your unique data. And every report is personally reviewed before it reaches you.",
  },
  {
    q: "Is this therapy or a diagnosis?",
    a: "No. TruKode is not therapy, does not diagnose or treat any condition, and is not a replacement for professional mental health support. It's a personal foundation for understanding yourself more clearly.",
  },
  {
    q: 'Is this a personality quiz or a "type"?',
    a: "No. You won't be placed in a box or reduced to a type. Every Read is built entirely from your own unique data — no two are ever the same.",
  },
  {
    q: "How accurate is it, and what should I expect?",
    a: "Expect a meaningful, deeply personal foundation — written in possibilities and tendencies, not absolutes. It's a place to begin and return to, not a quick fix or a final destination.",
  },
  {
    q: "How do I receive my Read?",
    a: "Instantly, as a beautifully formatted PDF you can download right away — with a copy emailed to you, so it's always within reach.",
  },
  {
    q: "How long does it take?",
    a: "The guided intake takes just a few minutes, and your report is ready right away. There's no waiting period.",
  },
  {
    q: "Is my personal data private and safe?",
    a: "Yes. The details you share are handled with care and used only to create your personal report — nothing more.",
  },
  {
    q: "Can I get more than one Read?",
    a: "Absolutely. Each Read explores a different dimension of who you are. Many people start with the Personal Read™ as their foundation, then explore others over time.",
  },
  {
    q: "Do you offer refunds?",
    a: (
      <>
        Because each Read is personally generated for you, we handle refund
        requests thoughtfully and case by case — just reach out, and we&apos;ll
        make it right. <em>(Full policy coming soon.)</em>
      </>
    ),
  },
];

function FaqItem({ q, a }: { q: string; a: ReactNode }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="overflow-hidden rounded-[14px] border border-dark/10 bg-paper">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="flex w-full cursor-pointer items-center justify-between gap-[18px] border-none bg-none px-[clamp(20px,4vw,30px)] py-[24px] text-left"
      >
        <span className="font-serif text-[clamp(19px,3vw,23px)] font-semibold text-dark">
          {q}
        </span>
        <svg
          viewBox="0 0 24 24"
          width="20"
          height="20"
          fill="none"
          className={`flex-none transition-transform duration-[400ms] ease-[cubic-bezier(.2,.7,.2,1)] ${
            open ? "rotate-180" : ""
          }`}
        >
          <path
            d="M6 9l6 6 6-6"
            className="stroke-gold-strong"
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      </button>
      <div
        className="overflow-hidden transition-[max-height,opacity] duration-[500ms] ease-[cubic-bezier(.2,.7,.2,1)]"
        style={{
          maxHeight: open ? 520 : 0,
          opacity: open ? 1 : 0,
        }}
      >
        <p className="m-0 px-[clamp(20px,4vw,30px)] pb-[26px] text-[15.5px] leading-[1.7] text-dark-soft">
          {a}
        </p>
      </div>
    </div>
  );
}

export function FaqList() {
  return (
    <div className="flex flex-col gap-3">
      {FAQS.map((item) => (
        <FaqItem key={item.q} q={item.q} a={item.a} />
      ))}
    </div>
  );
}
